# Auto-generated FFTW configuration from pyFFTW wheel
# This file is generated by extract_fftw_from_pyfftw.py

set(FFTW_ROOT "/work/genalyzer/venv/lib/python3.12/site-packages")
set(FFTW_LIBRARY_DIR "/work/genalyzer/venv/lib/python3.12/site-packages/pyFFTW.libs")
# Note: FFTW headers not found in pyFFTW wheel
# You may need to download fftw3.h separately

set(CMAKE_PREFIX_PATH "/work/genalyzer/venv/lib/python3.12/site-packages/pyFFTW.libs" "${CMAKE_PREFIX_PATH}")
link_directories("/work/genalyzer/venv/lib/python3.12/site-packages/pyFFTW.libs")
