repos:
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.1
    hooks:
    -   id: insert-license
        files: bindings\/python\/genalyzer\/.*\.py$
        args:
        - --license-filepath
        - .github/license_header.txt
        - --use-current-year
        - --no-extra-eol
        - --detect-license-in-X-top-lines=3
