name: PyPI Testing Deploy

on: [push, pull_request]

jobs:
  PyPITestingDeploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          bash ./.github/scripts/install_dependencies.sh USER
          bash ./.github/scripts/install_genalyzer.sh
          sudo rm -rf build
          pip install setuptools wheel twine build

      - name: Update to dev version and build test release
        run: |
          pip install invoke
          invoke bumpversion-test
          cd bindings/python
          python -m build
          
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: github.ref == 'refs/heads/main'
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
          packages_dir: ./bindings/python/dist
