name: PyPI Deploy

on: [push, pull_request]

jobs:
  PyPIDeploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          bash ./.github/scripts/install_dependencies.sh USER
          bash ./.github/scripts/install_genalyzer.sh
          sudo rm -rf build
          pip install setuptools wheel twine build

      - name: Update to dev version and build test release
        run: |
          cd bindings/python
          python -m build
          
      - uses: pypa/gh-action-pypi-publish@v1.12.2
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
          packages_dir: ./bindings/python/dist
